### ISSUE TITLE
File upload saves as array

### ISSUE THREAD

**Issue by mikemartin** [edalzell/statamic-user-profile#1]
## Expected result
After saving the form, the file should be saved as a single asset.
`photo: /assets/headshots/content-attributes.jpg`

## Actual result
File upload is saved as an array.
```
photo: 
  - /assets/headshots/content-attributes.jpg
```

**Comment by edalzell** [comment]
Fixed in https://github.com/edalzell/statamic-user-profile/commit/7516da89172df3faeb474e30b2843aa281dbf1ea.
