### ISSUE TITLE
FR: Better username handling

### ISSUE THREAD

**Issue by iDGS** [edalzell/statamic-user-profile#5]
I d/l the 101 version, and yes I can get it wor-king, so THANKS VERY MUCH!!!

That said, I think there's a few additional things you might like to know. Here's the story…

If I lift what I consider to be pretty much the simplest case from the demo code in the ReadMe, I get:
```
        {{ user_profile:edit_form redirect="/member/update" files="true" }}
            {{ if errors }}
                <div class="alert alert-danger">
                    {{ errors }}
                    {{ value }}<br>
                    {{ /errors }}
                </div>
            {{ /if }}

            <div class="form-group">
                <label>First Name</label>
                <input type="text" name="first_name" value="{{ old:first_name or first_name }}" class="form-control" />
            </div>

            <div class="form-group">
                <label>Last Name</label>
                <input type="text" name="last_name" value="{{ old:last_name or last_name }}" class="form-control" />
            </div>

            <button class="btn btn-primary">Update</button>

        {{ /user_profile:edit_form }}
```

In other words, to get things rolling, I decided to start by seeing if I could update just the first and last name (and yes: `first_name` and `last_name` are valid fields).

What happens next, when I click "Update", is I get an error, saying: `The username is required.`

Eh, …?  I'm a little puzzled because I see that it *is* using the right data for the person I'm testing this on. So, somehow it already implicitly "knows" the username, because in this case the username is the FID, or File ID, in the form of `AUsername.yaml`.

Well, OK, I go back to the ReadMe and copy in another snippet wherein I find `username`, thus getting:
```
        {{ user_profile:edit_form redirect="/member/update" files="true" }}
            {{ if errors }}
                <div class="alert alert-danger">
                    {{ errors }}
                    {{ value }}<br>
                    {{ /errors }}
                </div>
            {{ /if }}

            <div class="form-group">
                <label>Email</label>
                <input type="email" name="email" value="{{ old:username or username }}" class="form-control" />
            </div>

            <div class="form-group">
                <label>First Name</label>
                <input type="text" name="first_name" value="{{ old:first_name or first_name }}" class="form-control" />
            </div>

            <div class="form-group">
                <label>Last Name</label>
                <input type="text" name="last_name" value="{{ old:last_name or last_name }}" class="form-control" />
            </div>

            <button class="btn btn-primary">Update</button>

        {{ /user_profile:edit_form }}
```
(That's it above, just after the error block.)

No surprise, what I get on the page is exactly what it says: a label "Email" but… inside the edit field is the FID prefix, e.g., `AUsername`. (Not a surprise, as that's what the code says to do.) So clearly, it's taking the FID as the username, which is good. But it's not in this case (by design of this particular site), a full-blown email address. So, if I do nothing else and just click "Update", it red-rims the field and pops up "Please enter an email address."  (likely because there's no @whatev) Which is not what I want it to do.

Easy work-around: I edit that last-inserted snippet so that it instead reads:
```
            <div class="form-group">
                <label>Username</label>
                <input type="text" name="username" value="{{ old:username or username }}" class="form-control" />
            </div>
```
And how if I just click "Update",… Ta-DAH!  it works! Yay!

Except there's an unwanted side-effect: In the file `AUsername.yaml` there's now a new field that the add-on inserted that wasn't there before: `username: AUsername`.

Eh,... ?

Well, OK, so next I try changing the first and last name fields… and THAT works! (Meaning I looked in the file and sure enuf, the values are the new gibberish I typed into the form.) Yay!

Then for grins I try changing the Username field… and *THAT* WORKS!!!! 

WOW!!! I'm impressed! I'm impressed not only because it changed the value in the (I-don't-really-want-it) `username` field, but I'm impressed because it also RENAMED THE FILE! `AUsername.yaml` is gone; and `ANewusername.yaml` is now present! YAY! So it really *did* change the username according to my I'm-not-using-email-addresses-as-usernames paradigm. Hot stuff!!

Gotta say: I really, REALLY LIKE being able to rename the users profile file from the front end!

So where's the beef?

Maybe these are just quibbles in comparison to the good news above? Nevertheless, in the spirit of offering constructive feedback:

1) I don't think the form should *require* (apparently via code buried in the add-on) the username field be present in order for the "Update" button to work. Maybe some folks don't want that rename-the-user capability to be on the form. (I guess my work-around will maybe be to make it off-screen/invisible to non-admins.)

2) Since the FID *can* be sufficient to contain the username, I don't think the form should force-create an explicit `username` field if one doesn't exist. (Is that really necessary? I dunno; maybe it's related to…)

3) I don't think the add-on should assume (as I'm kinda guessing it does) that the username is an email address. I know that email addresses for login are a way to go; I've not done that here. Maybe it's a better way, but generally I think a way-neutral approach (where either method is equally OK) would be a better.

4) Honeypot for trapping nasty bots? Maybe too much to include in your ReadMe example? But I think it would sure be handy...

5) I'm stumped. I can get a select field's current value into the label, but I can't quite figure out how to get that current value to be the one showing/already-selected in the active portion of a `<select><option><option>`... pop-up list. The idea being, if the page is presented as-is, and the user does nothing except tap "Update" (without having made any changes), nothing should change! Again, is an example of that too much to include in your ReadMe? It would sure be useful to me!

Consider these as RFEs? (Requests for Enhancements) 

Once again, many, many thanks!

**Comment by edalzell** [comment]
That's a lot of comments and suggestions. In the future, can you please break out your bugs and requests separately?

**Comment by iDGS** [comment]
You quick! Yep, that would be a better way. Thx.
